name: angel_couch
version: 0.0.1
description: CouchDB-enabled services for the Angel framework. Well-tested.
author: Lorendeaux O <vraptor.coder@outlook.com>
homepage: https://github.com/angel-dart/angel_mongo
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  angel_framework: ^2.1.1
  json_god: '>=2.0.0-beta <3.0.0'
  merge_map: ^1.0.0
  couchdb: '>= 0.0.6 <1.0.0'
  bson: '>=0.3.2'
dev_dependencies:
  http: '>= 0.11.3 <= 0.12.0'
  pedantic: ^1.9.0
  test: ^1.14.2
